"""The prefecture DCX assigns to each EX9 bit. The names are Japan's; the bit layout is DCX's.

The English is that of the DCR prefecture table, so that a prefecture reads the same in a DCR and
in a DCX report.
"""
from ...code_table import CodeTable

#: the bits EX9 gives the prefectures; the field's width, not the number of names below
EX9_PREFECTURE_BITS: int = 47

ex9_target_area_code_en = CodeTable(
    {
        1 << 0: 'Hokkaido Prefecture',
        1 << 1: 'Aomori Prefecture',
        1 << 2: 'Iwate Prefecture',
        1 << 3: 'Miyagi Prefecture',
        1 << 4: 'Akita Prefecture',
        1 << 5: 'Yamagata Prefecture',
        1 << 6: 'Fukushima Prefecture',
        1 << 7: 'Ibaraki Prefecture',
        1 << 8: 'Tochigi Prefecture',
        1 << 9: 'Gunma Prefecture',
        1 << 10: 'Saitama Prefecture',
        1 << 11: 'Chiba Prefecture',
        1 << 12: 'Tokyo Metropolis',
        1 << 13: 'Kanagawa Prefecture',
        1 << 14: 'Niigata Prefecture',
        1 << 15: 'Toyama Prefecture',
        1 << 16: 'Ishikawa Prefecture',
        1 << 17: 'Fukui Prefecture',
        1 << 18: 'Yamanashi Prefecture',
        1 << 19: 'Nagano Prefecture',
        1 << 20: 'Gifu Prefecture',
        1 << 21: 'Shizuoka Prefecture',
        1 << 22: 'Aichi Prefecture',
        1 << 23: 'Mie Prefecture',
        1 << 24: 'Shiga Prefecture',
        1 << 25: 'Kyoto Prefecture',
        1 << 26: 'Osaka Prefecture',
        1 << 27: 'Hyogo Prefecture',
        1 << 28: 'Nara Prefecture',
        1 << 29: 'Wakayama Prefecture',
        1 << 30: 'Tottori Prefecture',
        1 << 31: 'Shimane Prefecture',
        1 << 32: 'Okayama Prefecture',
        1 << 33: 'Hiroshima Prefecture',
        1 << 34: 'Yamaguchi Prefecture',
        1 << 35: 'Tokushima Prefecture',
        1 << 36: 'Kagawa Prefecture',
        1 << 37: 'Ehime Prefecture',
        1 << 38: 'Kochi Prefecture',
        1 << 39: 'Fukuoka Prefecture',
        1 << 40: 'Saga Prefecture',
        1 << 41: 'Nagasaki Prefecture',
        1 << 42: 'Kumamoto Prefecture',
        1 << 43: 'Oita Prefecture',
        1 << 44: 'Miyazaki Prefecture',
        1 << 45: 'Kagoshima Prefecture',
        1 << 46: 'Okinawa Prefecture',
    },
    undefined = 'Undefined prefecture in Japan (Code: %d)'
)


ex9_target_area_code_ja = CodeTable(
    {
        1 << 0: '北海道',
        1 << 1: '青森県',
        1 << 2: '岩手県',
        1 << 3: '宮城県',
        1 << 4: '秋田県',
        1 << 5: '山形県',
        1 << 6: '福島県',
        1 << 7: '茨城県',
        1 << 8: '栃木県',
        1 << 9: '群馬県',
        1 << 10: '埼玉県',
        1 << 11: '千葉県',
        1 << 12: '東京都',
        1 << 13: '神奈川県',
        1 << 14: '新潟県',
        1 << 15: '富山県',
        1 << 16: '石川県',
        1 << 17: '福井県',
        1 << 18: '山梨県',
        1 << 19: '長野県',
        1 << 20: '岐阜県',
        1 << 21: '静岡県',
        1 << 22: '愛知県',
        1 << 23: '三重県',
        1 << 24: '滋賀県',
        1 << 25: '京都府',
        1 << 26: '大阪府',
        1 << 27: '兵庫県',
        1 << 28: '奈良県',
        1 << 29: '和歌山県',
        1 << 30: '鳥取県',
        1 << 31: '島根県',
        1 << 32: '岡山県',
        1 << 33: '広島県',
        1 << 34: '山口県',
        1 << 35: '徳島県',
        1 << 36: '香川県',
        1 << 37: '愛媛県',
        1 << 38: '高知県',
        1 << 39: '福岡県',
        1 << 40: '佐賀県',
        1 << 41: '長崎県',
        1 << 42: '熊本県',
        1 << 43: '大分県',
        1 << 44: '宮崎県',
        1 << 45: '鹿児島県',
        1 << 46: '沖縄県',
    },
    undefined = '都道府県(コード番号: %d)'
)
