from .qzss_dcr_definition import QzssDcrDefinition


qzss_dcx_camf_ex9_target_area_code = QzssDcrDefinition(
    {
        1 << 0: 'Hokkaido',
        1 << 1: 'Aomori',
        1 << 2: 'Iwate',
        1 << 3: 'Miyagi',
        1 << 4: 'Akita',
        1 << 5: 'Yamagata',
        1 << 6: 'Fukushima',
        1 << 7: 'Ibaraki',
        1 << 8: 'Tochigi',
        1 << 9: 'Gunma',
        1 << 10: 'Saitama',
        1 << 11: 'Chiba',
        1 << 12: 'Tokyo',
        1 << 13: 'Kanagawa',
        1 << 14: 'Niigata',
        1 << 15: 'Toyama',
        1 << 16: 'Ishikawa',
        1 << 17: 'Fukui',
        1 << 18: 'Yamanashi',
        1 << 19: 'Nagano',
        1 << 20: 'Gifu',
        1 << 21: 'Shizuoka',
        1 << 22: 'Aichi',
        1 << 23: 'Mie',
        1 << 24: 'Shiga',
        1 << 25: 'Kyoto',
        1 << 26: 'Osaka',
        1 << 27: 'Hyogo',
        1 << 28: 'Nara',
        1 << 29: 'Wakayama',
        1 << 20: 'Tottori',
        1 << 31: 'Shimane',
        1 << 32: 'Okayama',
        1 << 33: 'Hiroshima',
        1 << 34: 'Yamaguchi',
        1 << 35: 'Tokushima',
        1 << 36: 'Kagawa',
        1 << 37: 'Ehime',
        1 << 38: 'Kochi',
        1 << 39: 'Fukuoka',
        1 << 40: 'Saga',
        1 << 41: 'Nagasaki',
        1 << 42: 'Kumamoto',
        1 << 43: 'Oita',
        1 << 44: 'Miyazaki',
        1 << 45: 'Kagoshima',
        1 << 46: 'Okinawa',
    },
    undefined = 'Undefined prefecture in Japan (Code: %d)'
)