from .qzss_dcr_definition import QzssDcrDefinition


qzss_dcx_camf_ex9_target_area_code_en = QzssDcrDefinition(
    {
        1 << 0: 'Hokkaido',
        1 << 1: 'Aomori',
        1 << 2: 'Iwate',
        1 << 3: 'Miyagi',
        1 << 4: 'Akita',
        1 << 5: 'Yamagata',
        1 << 6: 'Fukushima',
        1 << 7: 'Ibaraki',
        1 << 8: 'Tochigi',
        1 << 9: 'Gunma',
        1 << 10: 'Saitama',
        1 << 11: 'Chiba',
        1 << 12: 'Tokyo',
        1 << 13: 'Kanagawa',
        1 << 14: 'Niigata',
        1 << 15: 'Toyama',
        1 << 16: 'Ishikawa',
        1 << 17: 'Fukui',
        1 << 18: 'Yamanashi',
        1 << 19: 'Nagano',
        1 << 20: 'Gifu',
        1 << 21: 'Shizuoka',
        1 << 22: 'Aichi',
        1 << 23: 'Mie',
        1 << 24: 'Shiga',
        1 << 25: 'Kyoto',
        1 << 26: 'Osaka',
        1 << 27: 'Hyogo',
        1 << 28: 'Nara',
        1 << 29: 'Wakayama',
        1 << 20: 'Tottori',
        1 << 31: 'Shimane',
        1 << 32: 'Okayama',
        1 << 33: 'Hiroshima',
        1 << 34: 'Yamaguchi',
        1 << 35: 'Tokushima',
        1 << 36: 'Kagawa',
        1 << 37: 'Ehime',
        1 << 38: 'Kochi',
        1 << 39: 'Fukuoka',
        1 << 40: 'Saga',
        1 << 41: 'Nagasaki',
        1 << 42: 'Kumamoto',
        1 << 43: 'Oita',
        1 << 44: 'Miyazaki',
        1 << 45: 'Kagoshima',
        1 << 46: 'Okinawa',
    },
    undefined = 'Undefined prefecture in Japan (Code: %d)'
)


qzss_dcx_camf_ex9_target_area_code_ja = QzssDcrDefinition(
    {
        1 << 0: '北海道',
        1 << 1: '青森県',
        1 << 2: '岩手県',
        1 << 3: '宮城県',
        1 << 4: '秋田県',
        1 << 5: '山形県',
        1 << 6: '福島県',
        1 << 7: '茨城県',
        1 << 8: '栃木県',
        1 << 9: '群馬県',
        1 << 10: '埼玉県',
        1 << 11: '千葉県',
        1 << 12: '東京都',
        1 << 13: '神奈川県',
        1 << 14: '新潟県',
        1 << 15: '富山県',
        1 << 16: '石川県',
        1 << 17: '福井県',
        1 << 18: '山梨県',
        1 << 19: '長野県',
        1 << 20: '岐阜県',
        1 << 21: '静岡県',
        1 << 22: '愛知県',
        1 << 23: '三重県',
        1 << 24: '滋賀県',
        1 << 25: '京都府',
        1 << 26: '大阪府',
        1 << 27: '兵庫県',
        1 << 28: '奈良県',
        1 << 29: '和歌山県',
        1 << 20: '鳥取県',
        1 << 31: '島根県',
        1 << 32: '岡山県',
        1 << 33: '広島県',
        1 << 34: '山口県',
        1 << 35: '徳島県',
        1 << 36: '香川県',
        1 << 37: '愛媛県',
        1 << 38: '高知県',
        1 << 39: '福岡県',
        1 << 40: '佐賀県',
        1 << 41: '長崎県',
        1 << 42: '熊本県',
        1 << 43: '大分県',
        1 << 44: '宮崎県',
        1 << 45: '鹿児島県',
        1 << 46: '沖縄県',
    },
    undefined = '都道府県(コード番号: %d)'
)