#pragma once
// AUTO-GENERATED from azarashi 0.15.1 — do not edit
// Source module : qzss_dcx_camf_a4_hazard_category_and_type
// Variable      : qzss_dcx_camf_a4_hazard_type
// Entries       : 113
// Strategy      : array

#include <cstdint>

namespace azaraC {
namespace def {

inline constexpr const char* QZSS_DCX_CAMF_A4_HAZARD_TYPE_TABLE[] = {
    "Air strike",
    "Attack on IT systems",
    "Attack with nuclear weapons",
    "Biological hazard",
    "Chemical hazard",
    "Explosive hazard",
    "Meteorite impact",
    "Missile attack",
    "Nuclear hazard",
    "Nuclear power station accident",
    "Radiological hazard",
    "Satellite/space re-entry debris",
    "Siren test",
    "Acid rain",
    "Air pollution",
    "Contaminated drinking water",
    "Gas leak",
    "Marine pollution",
    "Noise pollution",
    "Plague of insects",
    "River pollution",
    "Suspended dust",
    "UV radiation",
    "Conflagration",
    "Fire brigade deployment",
    "Fire gases",
    "Forest fire",
    "Fumes",
    "Odour nuisance",
    "Risk of fire",
    "Structure fire / Industrial fire",
    "Ash fall",
    "Avalanche risk",
    "Crack in the ground / sinkhole",
    "Debris flow",
    "Earthquake",
    "Geomagnetic or solar storm",
    "Glacial ice avalanche",
    "Landslide",
    "Lava flow",
    "Pyroclastic flow",
    "Snowdrifts",
    "Tidal wave",
    "Tsunami",
    "Volcanic mud flow",
    "Volcano eruption",
    "Wind / wave / storm surge",
    "Epizootic",
    "Food safety alert",
    "Health hazard",
    "Pandemic",
    "Pest infestation",
    "Risk of infection",
    "Building collapse",
    "Emergency number outage",
    "Gas supply outage",
    "Outage of IT systems",
    "Power outage",
    "Raw sewage",
    "Telephone line outage",
    "Black Ice",
    "Coastal flooding",
    "Cold wave",
    "Derecho",
    "Drought",
    "Dust storm",
    "Floating ice / icebergs",
    "Flood",
    "Fog",
    "Hail",
    "Heat wave",
    "Lightning",
    "Pollens",
    "Rainfall",
    "Snow storm / blizzard",
    "Snowfall",
    "Storm or thunderstorm",
    "Thawing",
    "Tornado",
    "Tropical cyclone (hurricane)",
    "Wind chill / frost",
    "Tropical cyclone (typhoon)",
    "Dam failure or bursting of a dam",
    "Dike failure or bursting of a dike",
    "Explosive ordnance disposal",
    "Factory accident",
    "Mine hazard",
    "Bomb / ammunition discovery",
    "Demonstration",
    "Hazardous material accident",
    "Life Threatening situation",
    "Major event",
    "Missing person / abduction",
    "Risk of explosion",
    "Safety warning",
    "Undefined flying object",
    "Unidentified animal",
    "Chemical attack",
    "Guerrilla attack",
    "Hijack",
    "Shooting or danger due to weapons",
    "Special forces attack",
    "Terrorism",
    "Aircraft crash",
    "Bridge collapse",
    "Dangerous goods accident",
    "Inland waterway transport accident",
    "Nautical disaster / Maritime / Marine Security",
    "Oil spill",
    "Road traffic incident",
    "Train/rail accident",
    "Tunnel accident",
    "Test alert"
};
inline constexpr uint8_t QZSS_DCX_CAMF_A4_HAZARD_TYPE_BASE = 1;
inline constexpr uint8_t QZSS_DCX_CAMF_A4_HAZARD_TYPE_SIZE = 113;
inline constexpr const char* qzss_dcx_camf_a4_hazard_type_lookup(uint8_t id) {
    if (id < QZSS_DCX_CAMF_A4_HAZARD_TYPE_BASE || id >= QZSS_DCX_CAMF_A4_HAZARD_TYPE_BASE + QZSS_DCX_CAMF_A4_HAZARD_TYPE_SIZE) return nullptr;
    return QZSS_DCX_CAMF_A4_HAZARD_TYPE_TABLE[id - QZSS_DCX_CAMF_A4_HAZARD_TYPE_BASE];
}

} // namespace def
} // namespace azaraC
