"""Epicenter and hypocenter names, IS-QZSS-DCR-017 Table 4.1.2-7.

The English names are JMA's, from its multilingual dictionary of weather information terms
(気象情報等に関する多言語辞書, updated 2026-03-26), matched by the code of the JMA XML code table AreaEpicenter
and AreaEpicenterAbbreviation, where the Japanese name is the same. Doubled or invisible spaces and
full-width brackets are tidied; the words are the dictionary's. The English for the DCR's own
names, 0, 999 and 1000, is azarashi's, but Northwest Pacific Tsunami Advisory in 0 is the
dictionary's name for 北西太平洋津波情報.
"""
from ...code_table import CodeTable

epicenter_and_hypocenter = CodeTable(
    {
        0: "未設定(北西太平洋津波情報)",
        11: "北海道地方",
        12: "東北地方",
        13: "北陸地方",
        14: "関東甲信地方",
        15: "小笠原地方",
        16: "東海地方",
        17: "近畿地方",
        18: "中国地方",
        19: "四国地方",
        20: "九州地方",
        21: "沖縄地方",
        100: "石狩地方北部",
        101: "石狩地方中部",
        102: "石狩地方南部",
        105: "渡島地方北部",
        106: "渡島地方東部",
        107: "渡島地方西部",
        110: "檜山地方",
        115: "後志地方北部",
        116: "後志地方東部",
        117: "後志地方西部",
        120: "空知地方北部",
        121: "空知地方中部",
        122: "空知地方南部",
        125: "上川地方北部",
        126: "上川地方中部",
        127: "上川地方南部",
        130: "留萌地方中北部",
        131: "留萌地方南部",
        135: "宗谷地方北部",
        136: "宗谷地方南部",
        140: "網走地方",
        141: "北見地方",
        142: "紋別地方",
        145: "胆振地方西部",
        146: "胆振地方中東部",
        150: "日高地方西部",
        151: "日高地方中部",
        152: "日高地方東部",
        155: "十勝地方北部",
        156: "十勝地方中部",
        157: "十勝地方南部",
        160: "釧路地方北部",
        161: "釧路地方中南部",
        165: "根室地方北部",
        166: "根室地方中部",
        167: "根室地方南部",
        180: "北海道南西沖",
        181: "北海道西方沖",
        182: "石狩湾",
        183: "北海道北西沖",
        184: "宗谷海峡",
        186: "国後島付近",
        187: "択捉島付近",
        188: "北海道東方沖",
        189: "根室半島南東沖",
        190: "釧路沖",
        191: "十勝沖",
        192: "浦河沖",
        193: "苫小牧沖",
        194: "内浦湾",
        195: "宗谷東方沖",
        196: "網走沖",
        197: "択捉島南東沖",
        200: "青森県津軽北部",
        201: "青森県津軽南部",
        202: "青森県三八上北地方",
        203: "青森県下北地方",
        210: "岩手県沿岸北部",
        211: "岩手県沿岸南部",
        212: "岩手県内陸北部",
        213: "岩手県内陸南部",
        220: "宮城県北部",
        221: "宮城県南部",
        222: "宮城県中部",
        230: "秋田県沿岸北部",
        231: "秋田県沿岸南部",
        232: "秋田県内陸北部",
        233: "秋田県内陸南部",
        240: "山形県庄内地方",
        241: "山形県最上地方",
        242: "山形県村山地方",
        243: "山形県置賜地方",
        250: "福島県中通り",
        251: "福島県浜通り",
        252: "福島県会津",
        280: "津軽海峡",
        281: "山形県沖",
        282: "秋田県沖",
        283: "青森県西方沖",
        284: "陸奥湾",
        285: "青森県東方沖",
        286: "岩手県沖",
        287: "宮城県沖",
        288: "三陸沖",
        289: "福島県沖",
        300: "茨城県北部",
        301: "茨城県南部",
        309: "千葉県南東沖",
        310: "栃木県北部",
        311: "栃木県南部",
        320: "群馬県北部",
        321: "群馬県南部",
        330: "埼玉県北部",
        331: "埼玉県南部",
        332: "埼玉県秩父地方",
        340: "千葉県北東部",
        341: "千葉県北西部",
        342: "千葉県南部",
        349: "房総半島南方沖",
        350: "東京都２３区",
        351: "東京都多摩東部",
        352: "東京都多摩西部",
        360: "神奈川県東部",
        361: "神奈川県西部",
        370: "新潟県上越地方",
        371: "新潟県中越地方",
        372: "新潟県下越地方",
        378: "新潟県下越沖",
        379: "新潟県上中越沖",
        380: "富山県東部",
        381: "富山県西部",
        390: "石川県能登地方",
        391: "石川県加賀地方",
        400: "福井県嶺北",
        401: "福井県嶺南",
        411: "山梨県中・西部",
        412: "山梨県東部・富士五湖",
        420: "長野県北部",
        421: "長野県中部",
        422: "長野県南部",
        430: "岐阜県飛騨地方",
        431: "岐阜県美濃東部",
        432: "岐阜県美濃中西部",
        440: "静岡県伊豆地方",
        441: "静岡県東部",
        442: "静岡県中部",
        443: "静岡県西部",
        450: "愛知県東部",
        451: "愛知県西部",
        460: "三重県北部",
        461: "三重県中部",
        462: "三重県南部",
        469: "三重県南東沖",
        471: "茨城県沖",
        472: "関東東方沖",
        473: "千葉県東方沖",
        475: "八丈島東方沖",
        476: "八丈島近海",
        477: "東京湾",
        478: "相模湾",
        480: "伊豆大島近海",
        481: "伊豆半島東方沖",
        482: "三宅島近海",
        483: "新島・神津島近海",
        485: "駿河湾",
        486: "駿河湾南方沖",
        487: "遠州灘",
        489: "三河湾",
        490: "伊勢湾",
        492: "若狭湾",
        493: "福井県沖",
        494: "石川県西方沖",
        495: "能登半島沖",
        497: "富山湾",
        498: "佐渡付近",
        499: "東海道南方沖",
        500: "滋賀県北部",
        501: "滋賀県南部",
        510: "京都府北部",
        511: "京都府南部",
        520: "大阪府北部",
        521: "大阪府南部",
        530: "兵庫県北部",
        531: "兵庫県南東部",
        532: "兵庫県南西部",
        540: "奈良県",
        550: "和歌山県北部",
        551: "和歌山県南部",
        560: "鳥取県東部",
        562: "鳥取県中部",
        563: "鳥取県西部",
        570: "島根県東部",
        571: "島根県西部",
        580: "岡山県北部",
        581: "岡山県南部",
        590: "広島県北部",
        591: "広島県南東部",
        592: "広島県南西部",
        600: "徳島県北部",
        601: "徳島県南部",
        610: "香川県東部",
        611: "香川県西部",
        620: "愛媛県東予",
        621: "愛媛県中予",
        622: "愛媛県南予",
        630: "高知県東部",
        631: "高知県中部",
        632: "高知県西部",
        673: "土佐湾",
        674: "紀伊水道",
        675: "大阪湾",
        676: "播磨灘",
        677: "瀬戸内海中部",
        678: "安芸灘",
        679: "周防灘",
        680: "伊予灘",
        681: "豊後水道",
        682: "山口県北西沖",
        683: "島根県沖",
        684: "鳥取県沖",
        685: "隠岐島近海",
        686: "兵庫県北方沖",
        687: "京都府沖",
        688: "淡路島付近",
        689: "和歌山県南方沖",
        700: "山口県北部",
        702: "山口県西部",
        703: "山口県東部",
        704: "山口県中部",
        710: "福岡県福岡地方",
        711: "福岡県北九州地方",
        712: "福岡県筑豊地方",
        713: "福岡県筑後地方",
        720: "佐賀県北部",
        721: "佐賀県南部",
        730: "長崎県北部",
        731: "長崎県南西部",
        732: "長崎県島原半島",
        740: "熊本県阿蘇地方",
        741: "熊本県熊本地方",
        742: "熊本県球磨地方",
        743: "熊本県天草・芦北地方",
        750: "大分県北部",
        751: "大分県中部",
        752: "大分県南部",
        753: "大分県西部",
        760: "宮崎県北部平野部",
        761: "宮崎県北部山沿い",
        762: "宮崎県南部平野部",
        763: "宮崎県南部山沿い",
        770: "鹿児島県薩摩地方",
        771: "鹿児島県大隅地方",
        783: "五島列島近海",
        784: "天草灘",
        785: "有明海",
        786: "橘湾",
        787: "鹿児島湾",
        790: "種子島近海",
        791: "日向灘",
        793: "奄美大島近海",
        795: "壱岐・対馬近海",
        796: "福岡県北西沖",
        797: "薩摩半島西方沖",
        798: "トカラ列島近海",
        799: "奄美大島北西沖",
        820: "大隅半島東方沖",
        821: "九州地方南東沖",
        822: "種子島南東沖",
        823: "奄美大島北東沖",
        850: "沖縄本島近海",
        851: "南大東島近海",
        852: "沖縄本島南方沖",
        853: "宮古島近海",
        854: "石垣島近海",
        855: "石垣島南方沖",
        856: "西表島付近",
        857: "与那国島近海",
        858: "沖縄本島北西沖",
        859: "宮古島北西沖",
        860: "石垣島北西沖",
        900: "台湾付近",
        901: "東シナ海",
        902: "四国沖",
        903: "鳥島近海",
        904: "鳥島東方沖",
        905: "オホーツク海南部",
        906: "サハリン西方沖",
        907: "日本海北部",
        908: "日本海中部",
        909: "日本海西部",
        911: "父島近海",
        912: "千島列島",
        913: "千島列島南東沖",
        914: "北海道南東沖",
        915: "東北地方東方沖",
        916: "小笠原諸島西方沖",
        917: "硫黄島近海",
        918: "小笠原諸島東方沖",
        919: "南海道南方沖",
        920: "薩南諸島東方沖",
        921: "本州南方沖",
        922: "サハリン南部付近",
        930: "北西太平洋",
        932: "マリアナ諸島",
        933: "黄海",
        934: "朝鮮半島南部",
        935: "朝鮮半島北部",
        936: "中国東北部",
        937: "ウラジオストク付近",
        938: "シベリア南部",
        939: "サハリン近海",
        940: "アリューシャン列島",
        941: "カムチャツカ半島付近",
        942: "北米西部",
        943: "北米中部",
        944: "北米東部",
        945: "中米",
        946: "南米西部",
        947: "南米中部",
        948: "南米東部",
        949: "北東太平洋",
        950: "南太平洋",
        951: "インドシナ半島付近",
        952: "フィリピン付近",
        953: "インドネシア付近",
        954: "グアム付近",
        955: "ニューギニア付近",
        956: "ニュージーランド付近",
        957: "オーストラリア付近",
        958: "シベリア付近",
        959: "ロシア西部",
        960: "ロシア中部",
        961: "ロシア東部",
        962: "中央アジア",
        963: "中国西部",
        964: "中国中部",
        965: "中国東部",
        966: "インド付近",
        967: "インド洋",
        968: "中東",
        969: "ヨーロッパ西部",
        970: "ヨーロッパ中部",
        971: "ヨーロッパ東部",
        972: "地中海",
        973: "アフリカ西部",
        974: "アフリカ中部",
        975: "アフリカ東部",
        976: "北大西洋",
        977: "南大西洋",
        978: "北極付近",
        979: "南極付近",
        999: "遠地",
        1000: "その他の震央地名",
        # "NNN*": "震央地名(コード番号：NNN)",
    },
    undefined="震央地名(コード番号：%d)"
)


epicenter_and_hypocenter_en = CodeTable(
    {
        0: "Not set (Northwest Pacific Tsunami Advisory)",
        11: "Hokkaido Region",
        12: "Tohoku Region",
        13: "Hokuriku Region",
        14: "Kanto Koushin Region",
        15: "Ogasawara Region",
        16: "Tokai Region",
        17: "Kinki Region",
        18: "Chugoku Region",
        19: "Shikoku Region",
        20: "Kyushu Region",
        21: "Okinawa Region",
        100: "Northern Ishikari Region, Hokkaido",
        101: "Central Ishikari Region, Hokkaido",
        102: "Southern Ishikari Region, Hokkaido",
        105: "Northern Oshima Region, Hokkaido",
        106: "Eastern Oshima Region, Hokkaido",
        107: "Western Oshima Region, Hokkaido",
        110: "Hiyama Region, Hokkaido",
        115: "Northern Shiribeshi Region, Hokkaido",
        116: "Eastern Shiribeshi Region, Hokkaido",
        117: "Western Shiribeshi Region, Hokkaido",
        120: "Northern Sorachi Region, Hokkaido",
        121: "Central Sorachi Region, Hokkaido",
        122: "Southern Sorachi Region, Hokkaido",
        125: "Northern Kamikawa Region, Hokkaido",
        126: "Central Kamikawa Region, Hokkaido",
        127: "Southern Kamikawa Region, Hokkaido",
        130: "Central and northern Rumoi Region, Hokkaido",
        131: "Southern Rumoi Region, Hokkaido",
        135: "Northern Soya Region, Hokkaido",
        136: "Southern Soya Region, Hokkaido",
        140: "Abashiri Region, Hokkaido",
        141: "Kitami Region, Hokkaido",
        142: "Mombetsu Region, Hokkaido",
        145: "Western Iburi Region, Hokkaido",
        146: "Central and eastern Iburi Region, Hokkaido",
        150: "Western Hidaka Region, Hokkaido",
        151: "Central Hidaka Region, Hokkaido",
        152: "Eastern Hidaka Region, Hokkaido",
        155: "Northern Tokachi Region, Hokkaido",
        156: "Central Tokachi Region, Hokkaido",
        157: "Southern Tokachi Region, Hokkaido",
        160: "Northern Kushiro Region, Hokkaido",
        161: "Central and southern Kushiro Region, Hokkaido",
        165: "Northern Nemuro Region, Hokkaido",
        166: "Central Nemuro Region, Hokkaido",
        167: "Southern Nemuro Region, Hokkaido",
        180: "Off the southwest Coast of Hokkaido",
        181: "Off the west Coast of Hokkaido",
        182: "Ishikari Bay",
        183: "Off the northwest Coast of Hokkaido",
        184: "Soya Strait",
        186: "Adjacent Kunashiri Island",
        187: "Adjacent Etorofu Island",
        188: "Off the east Coast of Hokkaido",
        189: "Off the southeast Coast of the Nemuro Peninsula",
        190: "Off the Coast of Kushiro",
        191: "Off the Coast of Tokachi",
        192: "Off the Coast of Urakawa",
        193: "Off the Coast of Tomakomai",
        194: "Uchiura Bay",
        195: "Off the east Coast of Soya",
        196: "Off the Coast of Abashiri",
        197: "Off the southeast Coast of Etorofu Island",
        200: "Northern Tsugaru, Aomori Prefecture",
        201: "Southern Tsugaru, Aomori Prefecture",
        202: "Sanpachi-Kamikita Region, Aomori Prefecture",
        203: "Shimokita Region, Aomori Prefecture",
        210: "Northern Coast of Iwate Prefecture",
        211: "Southern Coast of Iwate Prefecture",
        212: "Northern Inland of Iwate Prefecture",
        213: "Southern Inland of Iwate Prefecture",
        220: "Northern Miyagi Prefecture",
        221: "Southern Miyagi Prefecture",
        222: "Central Miyagi Prefecture",
        230: "Northern Coast of Akita Prefecture",
        231: "Southern Coast of Akita Prefecture",
        232: "Northern Inland of Akita Prefecture",
        233: "Southern Inland of Akita Prefecture",
        240: "Shonai Region, Yamagata Prefecture",
        241: "Mogami Region, Yamagata Prefecture",
        242: "Murayama Region, Yamagata Prefecture",
        243: "Okitama Region, Yamagata Prefecture",
        250: "Nakadori, Fukushima Prefecture",
        251: "Hamadori, Fukushima Prefecture",
        252: "Aizu, Fukushima Prefecture",
        280: "Tsugaru Strait",
        281: "Off the Coast of Yamagata Prefecture",
        282: "Off the Coast of Akita Prefecture",
        283: "Off the west Coast of Aomori Prefecture",
        284: "Mutsu Bay",
        285: "Off the east Coast of Aomori Prefecture",
        286: "Off the Coast of Iwate Prefecture",
        287: "Off the Coast of Miyagi Prefecture",
        288: "Off the Coast of Sanriku",
        289: "Off the Coast of Fukushima Prefecture",
        300: "Northern Ibaraki Prefecture",
        301: "Southern Ibaraki Prefecture",
        309: "Off the southeast Coast of Chiba Prefecture",
        310: "Northern Tochigi Prefecture",
        311: "Southern Tochigi Prefecture",
        320: "Northern Gunma Prefecture",
        321: "Southern Gunma Prefecture",
        330: "Northern Saitama Prefecture",
        331: "Southern Saitama Prefecture",
        332: "Chichibu Region, Saitama Prefecture",
        340: "Northeastern Chiba Prefecture",
        341: "Northwestern Chiba Prefecture",
        342: "Southern Chiba Prefecture",
        349: "Off the south Coast of Boso Peninsula",
        350: "23 wards, Tokyo",
        351: "Eastern Tama, Tokyo",
        352: "Western Tama, Tokyo",
        360: "Eastern Kanagawa Prefecture",
        361: "Western Kanagawa Prefecture",
        370: "Joetsu, Niigata Prefecture",
        371: "Chuetsu, Niigata Prefecture",
        372: "Kaetsu, Niigata Prefecture",
        378: "Off the Coast of Kaetsu, Niigata Prefecture",
        379: "Off the Coast of Joetsu and Chuetsu, Niigata Prefecture",
        380: "Eastern Toyama Prefecture",
        381: "Western Toyama Prefecture",
        390: "Noto, Ishikawa Prefecture",
        391: "Kaga, Ishikawa Prefecture",
        400: "Reihoku, Fukui Prefecture",
        401: "Reinan, Fukui Prefecture",
        411: "Central · Western Yamanashi Prefecture",
        412: "Eastern Region · Fuji Five Lakes, Yamanashi Prefecture",
        420: "Northern Nagano Prefecture",
        421: "Central Nagano Prefecture",
        422: "Southern Nagano Prefecture",
        430: "Hida, Gifu Prefecture",
        431: "Eastern Mino, Gifu Prefecture",
        432: "Central and western Mino, Gifu Prefecture",
        440: "Izu, Shizuoka Prefecture",
        441: "Eastern Shizuoka Prefecture",
        442: "Central Shizuoka Prefecture",
        443: "Western Shizuoka Prefecture",
        450: "Eastern Aichi Prefecture",
        451: "Western Aichi Prefecture",
        460: "Northern Mie Prefecture",
        461: "Central Mie Prefecture",
        462: "Southern Mie Prefecture",
        469: "Off the southeast Coast of Mie Prefecture",
        471: "Off the Coast of Ibaraki Prefecture",
        472: "Off the east Coast of Kanto",
        473: "Off the east Coast of Chiba Prefecture",
        475: "Off the east Coast of Hachijojima Island",
        476: "Adjacent Sea of Hachijojima Island",
        477: "Tokyo Bay",
        478: "Sagami Bay",
        480: "Adjacent Sea of Izu-Oshima Island",
        481: "Off the east Coast of Izu Peninsula",
        482: "Adjacent Sea of Miyakejima Island",
        483: "Adjacent Sea of Niijima Island, Kozushima Island",
        485: "Suruga Bay",
        486: "Off the south Coast of Suruga Bay",
        487: "Enshunada Sea",
        489: "Mikawa Bay",
        490: "Ise Bay",
        492: "Wakasa Bay",
        493: "Off the Coast of Fukui Prefecture",
        494: "Off the west Coast of Ishikawa Prefecture",
        495: "Off the Coast of Noto Peninsula",
        497: "Toyama Bay",
        498: "Adjacent Sado",
        499: "Off the south Coast of Tokaido",
        500: "Northern Shiga Prefecture",
        501: "Southern Shiga Prefecture",
        510: "Northern Kyoto Prefecture",
        511: "Southern Kyoto Prefecture",
        520: "Northern Osaka Prefecture",
        521: "Southern Osaka Prefecture",
        530: "Northern Hyogo Prefecture",
        531: "Southeastern Hyogo Prefecture",
        532: "Southwestern Hyogo Prefecture",
        540: "Nara Prefecture",
        550: "Northern Wakayama Prefecture",
        551: "Southern Wakayama Prefecture",
        560: "Eastern Tottori Prefecture",
        562: "Central Tottori Prefecture",
        563: "Western Tottori Prefecture",
        570: "Eastern Shimane Prefecture",
        571: "Western Shimane Prefecture",
        580: "Northern Okayama Prefecture",
        581: "Southern Okayama Prefecture",
        590: "Northern Hiroshima Prefecture",
        591: "Southeastern Hiroshima Prefecture",
        592: "Southwestern Hiroshima Prefecture",
        600: "Northern Tokushima Prefecture",
        601: "Southern Tokushima Prefecture",
        610: "Eastern Kagawa Prefecture",
        611: "Western Kagawa Prefecture",
        620: "Toyo, Ehime Prefecture",
        621: "Chuyo, Ehime Prefecture",
        622: "Nanyo, Ehime Prefecture",
        630: "Eastern Kochi Prefecture",
        631: "Central Kochi Prefecture",
        632: "Western Kochi Prefecture",
        673: "Tosa Bay",
        674: "Kiisuido Strait",
        675: "Osaka Bay",
        676: "Harimanada Sea",
        677: "Central Setonaikai Sea",
        678: "Akinada Sea",
        679: "Suonada Sea",
        680: "Iyonada Sea",
        681: "Bungosuido Strait",
        682: "Off the northwest Coast of Yamaguchi Prefecture",
        683: "Off the Coast of Shimane Prefecture",
        684: "Off the Coast of Tottori Prefecture",
        685: "Adjacent Sea of Oki Islands",
        686: "Off the north Coast of Hyogo Prefecture",
        687: "Off the Coast of Kyoto Prefecture",
        688: "Adjacent Awajishima Island",
        689: "Off the south Coast of Wakayama Prefecture",
        700: "Northern Yamaguchi Prefecture",
        702: "Western Yamaguchi Prefecture",
        703: "Eastern Yamaguchi Prefecture",
        704: "Central Yamaguchi Prefecture",
        710: "Fukuoka Region, Fukuoka Prefecture",
        711: "Kitakyushu Region, Fukuoka Prefecture",
        712: "Chikuho Region, Fukuoka Prefecture",
        713: "Chikugo Region, Fukuoka Prefecture",
        720: "Northern Saga Prefecture",
        721: "Southern Saga Prefecture",
        730: "Northern Nagasaki Prefecture",
        731: "Southwestern Nagasaki Prefecture",
        732: "Shimabara Peninsula, Nagasaki Prefecture",
        740: "Aso Region, Kumamoto Prefecture",
        741: "Kumamoto Region, Kumamoto Prefecture",
        742: "Kuma Region, Kumamoto Prefecture",
        743: "Amakusa and Ashikita Region, Kumamoto Prefecture",
        750: "Northern Oita Prefecture",
        751: "Central Oita Prefecture",
        752: "Southern Oita Prefecture",
        753: "Western Oita Prefecture",
        760: "Plain Area of Northern Miyazaki Prefecture",
        761: "Area along Mountains of Northern Miyazaki Prefecture",
        762: "Plain Area of Southern Miyazaki Prefecture",
        763: "Area along Mountains of Southern Miyazaki Prefecture",
        770: "Satsuma Region, Kagoshima Prefecture",
        771: "Osumi Region, Kagoshima Prefecture",
        783: "Adjacent Sea of Goto Islands",
        784: "Amakusanada Sea",
        785: "Ariake Sea",
        786: "Tachibana Bay",
        787: "Kagoshima Bay",
        790: "Adjacent Sea of Tanegashima Island",
        791: "Hyuganada Sea",
        793: "Adjacent Sea of Amami-Oshima Island",
        795: "Adjacent Sea of Ikishima Island and Tsushima Island",
        796: "Off the northwest Coast of Fukuoka Prefecture",
        797: "Off the west Coast of Satsuma Peninsula",
        798: "Adjacent Sea of Tokara Islands",
        799: "Off the northwest Coast of Amami- Oshima Island",
        820: "Off the east Coast of Osumi Peninsula",
        821: "Off the southeast Coast of Kyushu",
        822: "Off the southeast Coast of Tanegashima Island",
        823: "Off the northeast Coast of Amami-Oshima Island",
        850: "Adjacent Sea of Okinawa Main Island",
        851: "Adjacent Sea of Minami-Daitojima Island",
        852: "Off the south Coast of Okinawa Main Island",
        853: "Adjacent Sea of Miyakojima Island",
        854: "Adjacent Sea of Ishigakijima Island",
        855: "Off the south Coast of Ishigakijima Island",
        856: "Adjacent Sea of Iriomotejima Island",
        857: "Adjacent Sea of Yonagunijima Island",
        858: "Off the northwest Coast of Okinawa Main Island",
        859: "Off the northwest Coast of Miyakojima Island",
        860: "Off the northwest Coast of Ishigakijima Island",
        900: "the vicinity of Taiwan",
        901: "East China Sea",
        902: "Off the Coast of Shikoku",
        903: "Adjacent Sea of Torishima Island",
        904: "Off the east Coast of Torishima Island",
        905: "Southern Sea of Okhotsk",
        906: "Off the west Coast of Sakhalin",
        907: "Northern Sea of Japan",
        908: "Central Sea of Japan",
        909: "Weatern Sea of Japan",
        911: "Adjacent Sea of Chichijima Island",
        912: "Kurile Islands",
        913: "Off the southeast Coast of Kurile Islands",
        914: "Off the southeast Coast of Hokkaido",
        915: "Off the east Coast of Tohoku",
        916: "Off the west Coast of Ogasawara Islands",
        917: "Adjacent Sea of Ioto Island",
        918: "Off the east Coast of Ogasawara Islands",
        919: "Off the south Coast of Nankaido",
        920: "Off the east Coast of Satsunan Islands",
        921: "Off the south Coast of Honshu",
        922: "Adjacent Southern Sakhalin",
        930: "Northwest Pacific Ocean",
        932: "Mariana Islands",
        933: "Yellow Sea",
        934: "Southern Korean Peninsula",
        935: "Northern Korean Peninsula",
        936: "Northeastern China",
        937: "Adjacent Vladivostok",
        938: "Southern Siberia",
        939: "Adjacent Sea of Sakhalin",
        940: "Aleutian Islands",
        941: "Adjacent Kamchatka Peninsula",
        942: "Western North America",
        943: "Central North America",
        944: "Eastern North America",
        945: "Central America",
        946: "Western South America",
        947: "Central South America",
        948: "Eastern South America",
        949: "Northeast Pacific Ocean",
        950: "South Pacific Ocean",
        951: "Adjacent Indochina Peninsula",
        952: "Adjacent Philippines",
        953: "Adjacent Indonesia",
        954: "Adjacent Guam",
        955: "Adjacent New Guinea",
        956: "Adjacent New Zealand",
        957: "Adjacent Australia",
        958: "Adjacent Siberia",
        959: "Western Russia",
        960: "Central Russia",
        961: "Eastern Russia",
        962: "Central Asia",
        963: "Western China",
        964: "Central China",
        965: "Eastern China",
        966: "Adjacent India",
        967: "Indian Ocean",
        968: "Middle East",
        969: "Western Europe",
        970: "Central Europe",
        971: "Eastern Europe",
        972: "Mediterranean",
        973: "Western Africa",
        974: "Central Africa",
        975: "Eastern Africa",
        976: "North Atlantic Ocean",
        977: "South Atlantic Ocean",
        978: "Near the North Pole",
        979: "Near the South Pole",
        999: "Distant",
        1000: "Other Epicenter",
    },
    undefined="Undefined Epicenter (Code: %d)"
)
