"""Tsunami forecast regions, IS-QZSS-DCR-017 Table 4.1.2-24.

The English names are JMA's, from its multilingual dictionary of weather information terms
(気象情報等に関する多言語辞書, updated 2026-03-26), matched by the code of the JMA XML code table AreaTsunami,
where the Japanese name is the same. Doubled or invisible spaces and full-width brackets are
tidied; the words are the dictionary's. The English for the DCR's own name, 1000, is azarashi's.
"""
from ...code_table import CodeTable

tsunami_forecast_region = CodeTable(
    {
        100: "北海道太平洋沿岸東部",
        101: "北海道太平洋沿岸中部",
        102: "北海道太平洋沿岸西部",
        110: "北海道日本海沿岸北部",
        111: "北海道日本海沿岸南部",
        120: "オホーツク海沿岸",
        191: "北海道太平洋沿岸",
        192: "北海道日本海沿岸",
        200: "青森県日本海沿岸",
        201: "青森県太平洋沿岸",
        202: "陸奥湾",
        210: "岩手県",
        220: "宮城県",
        230: "秋田県",
        240: "山形県",
        250: "福島県",
        281: "青森県",
        291: "東北地方太平洋沿岸",
        292: "東北地方日本海沿岸",
        300: "茨城県",
        310: "千葉県九十九里・外房",
        311: "千葉県内房",
        312: "東京湾内湾",
        320: "伊豆諸島",
        321: "小笠原諸島",
        330: "相模湾・三浦半島",
        340: "新潟県上中下越",
        341: "佐渡",
        350: "富山県",
        360: "石川県能登",
        361: "石川県加賀",
        370: "福井県",
        380: "静岡県",
        390: "愛知県外海",
        391: "伊勢・三河湾",
        400: "三重県南部",
        481: "千葉県",
        482: "神奈川県",
        483: "新潟県",
        484: "石川県",
        485: "愛知県",
        486: "三重県",
        491: "関東地方",
        492: "伊豆・小笠原諸島",
        493: "北陸地方",
        494: "東海地方",
        500: "京都府",
        510: "大阪府",
        520: "兵庫県北部",
        521: "兵庫県瀬戸内海沿岸",
        522: "淡路島南部",
        530: "和歌山県",
        540: "鳥取県",
        550: "島根県出雲・石見",
        551: "隠岐",
        560: "岡山県",
        570: "広島県",
        580: "徳島県",
        590: "香川県",
        600: "愛媛県宇和海沿岸",
        601: "愛媛県瀬戸内海沿岸",
        610: "高知県",
        681: "兵庫県",
        682: "島根県",
        683: "愛媛県",
        691: "近畿四国太平洋沿岸",
        692: "近畿中国日本海沿岸",
        693: "瀬戸内海沿岸",
        700: "山口県日本海沿岸",
        701: "山口県瀬戸内海沿岸",
        710: "福岡県瀬戸内海沿岸",
        711: "福岡県日本海沿岸",
        712: "有明・八代海",
        720: "佐賀県北部",
        730: "長崎県西方",
        731: "壱岐・対馬",
        740: "熊本県天草灘沿岸",
        750: "大分県瀬戸内海沿岸",
        751: "大分県豊後水道沿岸",
        760: "宮崎県",
        770: "鹿児島県東部",
        771: "種子島・屋久島地方",
        772: "奄美群島・トカラ列島",
        773: "鹿児島県西部",
        781: "山口県",
        782: "福岡県",
        783: "佐賀県",
        784: "長崎県",
        785: "熊本県",
        786: "大分県",
        787: "鹿児島県",
        791: "九州地方東部",
        792: "九州地方西部",
        793: "薩南諸島",
        800: "沖縄本島地方",
        801: "大東島地方",
        802: "宮古島・八重山地方",
        891: "沖縄県地方",
        1000: "その他の津波予報区",
        # "NNN": "津波予報区(コード番号：NNN)"",
    },
    undefined="津波予報区(コード番号：%d)"
)


tsunami_forecast_region_en = CodeTable(
    {
        100: "Eastern part of Pacific Coast of Hokkaido",
        101: "Central part of Pacific Coast of Hokkaido",
        102: "Western part of Pacific Coast of Hokkaido",
        110: "Northern part of Japan Sea Coast of Hokkaido",
        111: "Southern part of Japan Sea Coast of Hokkaido",
        120: "Okhotsk Sea Coast of Hokkaido",
        191: "Pacific Coast of Hokkaido",
        192: "Japan Sea Coast of Hokkaido",
        200: "Japan Sea Coast of Aomori Prefecture",
        201: "Pacific Coast of Aomori Prefecture",
        202: "Mutsu Bay",
        210: "Iwate Prefecture",
        220: "Miyagi Prefecture",
        230: "Akita Prefecture",
        240: "Yamagata Prefecture",
        250: "Fukushima Prefecture",
        281: "Aomori Prefecture",
        291: "Pacific Coast of Tohoku",
        292: "Japan Sea Coast of Tohoku",
        300: "Ibaraki Prefecture",
        310: "Kujukuri and Sotobo Area, Chiba Prefecture",
        311: "Uchibo Area, Chiba Prefecture",
        312: "Tokyo Bay",
        320: "Izu Islands",
        321: "Ogasawara Islands",
        330: "Sagami Bay and Miura Peninsula",
        340: "Niigata Prefecture, Except Sadogashima Island",
        341: "Sadogashima Island",
        350: "Toyama Prefecture",
        360: "Noto Area, Ishikawa Prefecture",
        361: "Kaga Area, Ishikawa Prefecture",
        370: "Fukui Prefecture",
        380: "Shizuoka Prefecture",
        390: "Pacific Coast of Aichi Prefecture",
        391: "Ise Bay and Mikawa Bay",
        400: "Southern Part of Mie Prefecture",
        481: "Chiba Prefecture",
        482: "Kanagawa Prefecture",
        483: "Niigata Prefecture",
        484: "Ishikawa Prefecture",
        485: "Aichi Prefecture",
        486: "Mie Prefecture",
        491: "Kanto",
        492: "Izu and Ogasawara",
        493: "Hokuriku",
        494: "Tokai",
        500: "Kyoto Prefecture",
        510: "Osaka Prefecture",
        520: "Northern Part of Hyogo Prefecture",
        521: "Setonaikai Coast of Hyogo Prefecture",
        522: "Southern Part of Awaji Island",
        530: "Wakayama Prefecture",
        540: "Tottori Prefecture",
        550: "Shimane Prefecture, Except Oki Islands",
        551: "Oki Islands",
        560: "Okayama Prefecture",
        570: "Hiroshima Prefecture",
        580: "Tokushima Prefecture",
        590: "Kagawa Prefecture",
        600: "Bungo Strait Coast of Ehime Prefecture",
        601: "Setonaikai Coast of Ehime Prefecture",
        610: "Kochi Prefecture",
        681: "Hyogo Prefecture",
        682: "Shimane Prefecture",
        683: "Ehime Prefecture",
        691: "Pacific Coast of Kinki/Shikoku",
        692: "Japan Sea Coast of Kinki/Chugoku",
        693: "Setonaikai Coast",
        700: "Japan Sea Coast of Yamaguchi Prefecture",
        701: "Setonaikai Coast of Yamaguchi Prefecture",
        710: "Setonaikai Coast of Fukuoka Prefecture",
        711: "Japan Sea Coast of Fukuoka Prefecture",
        712: "Ariake Sea and Yatsushiro Sea",
        720: "Northern Part of Saga Prefecture",
        730: "Western Part of Nagasaki Prefecture",
        731: "Iki Island and Tsushima Islands",
        740: "Amakusa Nada Coast of Kumamoto Prefecture",
        750: "Setonaikai Coast of Oita Prefecture",
        751: "Bungo Strait Coast of Oita Prefecture",
        760: "Miyazaki Prefecture",
        770: "Eastern Part of Kagoshima Prefecture",
        771: "Tanegashima and Yakushima Area",
        772: "Amami Islands and Tokara Islands",
        773: "Western Part of Kagoshima Prefecture",
        781: "Yamaguchi Prefecture",
        782: "Fukuoka Prefecture",
        783: "Saga Prefecture",
        784: "Nagasaki Prefecture",
        785: "Kumamoto Prefecture",
        786: "Ooita Prefecture",
        787: "Kagoshima Prefecture",
        791: "Eastern Part of Kyushu",
        792: "Western Part of Kyushu",
        793: "Satsunan Islands",
        800: "Okinawa Main Island Region",
        801: "Daitojima Area",
        802: "Miyakojima and Yaeyama Area",
        891: "Okinawa Prefecture",
        1000: "Other Tsunami Forecast Region",
    },
    undefined="Undefined Tsunami Forecast Region (Code: %d)"
)
